server {
	listen 80;

	# Serve alpine.js/html files
	location / {
		root /usr/share/nginx/html;
		index index.html;
	}

	# Proxy REST API requests
	location /api/ {
		proxy_pass http://backend:8000;
	}

	# Proxy websockets for live telemetry
	location /ws {
		proxy_pass http://backend:8000/ws;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}
}
